import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = path => readFile(new URL(path, import.meta.url), 'utf8');
const typing=await read('../js/modules/typing.js');
const inputController=await read('../js/input-controller.js');
const modes=await read('../js/modes/index.js');
const index=await read('../js/main.js');
const ui=await read('../js/modules/ui.js');
const audio=await read('../js/modules/audio.js');
const keyboard=await read('../js/keyboard-focus.js');
const tutorial=await read('../js/tutorial-navigation.js');
const memory=await read('../js/modes/memory.js');
const marathon=await read('../js/modes/marathon.js');
const wave=await read('../js/modes/wave.js');
const rpg=await read('../js/modes/rpg.js');
const utils=await read('../js/modules/utils.js');
const uiV3=await read('../js/ui-v3.js');
const html=await read('../index.html');

test('núcleo rejeita colagem, drop e substituição',()=>{assert.match(inputController,/insertFromPaste/);assert.match(inputController,/insertFromDrop/);assert.match(inputController,/insertReplacementText/);assert.match(inputController,/preventDefault/)});
test('contagem e áudio usam o input efetivo',()=>{assert.match(inputController,/const value=input\.value/);assert.match(inputController,/state\.totalTyped/);assert.match(inputController,/audioEngine\.playKey/);assert.match(index,/input-controller\.js/)});
test('reinícios internos sincronizam a base do controlador',()=>{assert.match(inputController,/syncAfterProgrammaticReset/);assert.match(inputController,/_controllerLastLength=0|_controllerLastLength = 0/)})
test('modos com temporizador recebem controle de timer próprio',()=>{assert.match(inputController,/mode\?\.hasTimer/);assert.match(inputController,/mode\.startTimer/);assert.match(marathon,/hasTimer:true/);assert.match(marathon,/startTimer\(/);assert.match(wave,/startWordTimer/)});
test('Maratona é distinta da Onda',()=>{assert.match(marathon,/timeLimit/);assert.match(marathon,/wordsTyped/);assert.match(wave,/waveIndex/);assert.match(wave,/timeForWord/)});
test('modo memória libera a entrada depois da fase de memorização',()=>{assert.match(memory,/input\)\{/);assert.match(memory,/readOnly=false/);assert.match(memory,/disabled=false/);assert.match(memory,/if\(!this\.hidden\)return/);assert.match(memory,/visibility='hidden'/)});
test('RPG inicializa texto e baseline da primeira batalha explicitamente',()=>{assert.match(rpg,/state\.currentText=text/);assert.match(rpg,/state\._controllerLastLength=0/);assert.match(rpg,/this\.battleOver=false/)});
test('encerramento protege contra processamento duplicado',()=>{assert.match(typing,/if\(state\._ending\)return/);assert.match(typing,/state\._testEnded=true/)});
test('há uma ação de continuação única para os dez modos ativos',()=>{assert.match(typing,/continue-mode-btn/);for(const id of ['default','fury','survival','sniper','wordhunt','casino','marathon','memory','wave','rpg'])assert.match(typing,new RegExp(id+':'))});
test('RPG usa a mesma ação compartilhada',()=>{assert.match(typing,/rpg:'⚔️ Continuar Batalhando'/);assert.match(typing,/continueBattle/);assert.doesNotMatch(rpg,/rpg-continue-btn/)});
test('prévia sonora não seleciona o perfil',()=>{assert.match(ui,/sound-preview-btn/);assert.match(ui,/audioEngine\.playPreview\(value\)/);assert.match(audio,/playPreview\(profile=this\.profile\)/);assert.match(audio,/playKey\(false,profile\)/)});
test('prévia não fecha o modal nem salva a seleção',()=>{assert.match(ui,/sound-preview-btn/);assert.match(ui,/audioEngine\.playPreview\(value\)/);assert.doesNotMatch(ui,/setSoundProfile\(value\).*closeModal\(modalSound\)/)});
test('Arco-Íris não faz mais parte do catálogo',()=>{assert.doesNotMatch(modes,/rainbowMode|rainbow:/);assert.doesNotMatch(modes,/Arco-Íris/);assert.doesNotMatch(utils,/rainbow:/)});
test('ajuda contextual está no cabeçalho da área de digitação e fora do painel',()=>{assert.match(uiV3,/typing-mode-info/);assert.match(uiV3,/typing-mode-control/);assert.match(uiV3,/ids:\['difficulty-trigger','theme-trigger','sound-trigger'\]/);assert.doesNotMatch(uiV3,/ids:\['difficulty-trigger','theme-trigger','sound-trigger','mode-help-trigger'/)});
test('painel não inclui o antigo controle de ajuda',()=>{assert.match(ui,/mode-help-trigger.*remove/);assert.doesNotMatch(uiV3,/mode-help-trigger'\]/)});
test('interface reduz seleção/context menu acidentais e acompanha o teclado',()=>{assert.match(keyboard,/-webkit-touch-callout:none/);assert.match(keyboard,/document\.addEventListener\('contextmenu'/);assert.match(keyboard,/scrollIntoView\(\{behavior:'smooth'/);assert.match(keyboard,/scrollTo\(\{top:savedScrollY,behavior:'smooth'/)});
test('tutorial possui navegação por clique e gesto',()=>{assert.match(index,/tutorial-navigation\.js/);assert.match(tutorial,/tutorial-next/);assert.match(tutorial,/tutorial-prev/);assert.match(tutorial,/touchstart/);assert.match(tutorial,/touchend/)});
test('tutorial atualizado para dez modos',()=>{assert.match(index,/10 modos/);assert.doesNotMatch(index,/11 modos/);assert.match(index,/⚔️ RPG/);assert.doesNotMatch(index,/🌈 Arco-Íris/)});
test('RPG continua escutando o ciclo próprio de batalha',()=>{assert.match(typing,/rpgReadyForContinue/);assert.match(rpg,/document\.dispatchEvent\(new CustomEvent\('rpgReadyForContinue'\)/)});
test('modo de jogo é reposicionado para a caixa de texto',()=>{assert.match(uiV3,/typing-mode-control/);assert.match(uiV3,/tags\.insertBefore\(modeGroup/)});
test('troca de modo destrói o anterior antes de inicializar o próximo',()=>{assert.match(modes,/currentMode\?\.destroy|currentMode&&currentMode\.destroy/);assert.match(modes,/initTest\(\{resetMode:false\}\)*/)});
