import { state, THEME_NAMES, SOUND_NAMES, DIFFICULTY_NAMES, DIFFICULTY_THRESHOLDS, getModeStats } from './utils.js';
import { loadAchievements, renderAchievementsUI, trackThemeChange, updateGlobalLevelUI } from './stats.js';
import { initTest } from './typing.js';
import { audioEngine } from './audio.js';
import { setMode, renderModeList, MODE_NAMES, getModeId, getModeHandler } from '../modes/index.js';

const difficultyTriggerText=document.getElementById('difficulty-trigger-text'),themeTriggerText=document.getElementById('theme-trigger-text'),soundTriggerText=document.getElementById('sound-trigger-text'),modeTriggerText=document.getElementById('mode-trigger-text'),difficultyTag=document.getElementById('difficulty-tag'),editCustomBtn=document.getElementById('edit-custom-btn'),restartBtn=document.getElementById('restart-btn'),medalsTitle=document.getElementById('medals-title'),standardMedals=document.getElementById('standard-medals'),customMedals=document.getElementById('custom-medals'),reqTime15=document.getElementById('req-time15'),reqTime30=document.getElementById('req-time30'),reqSpeed60=document.getElementById('req-speed60'),customTextInput=document.getElementById('custom-text-input'),customTextError=document.getElementById('custom-text-error'),saveCustomTextBtn=document.getElementById('save-custom-text-btn'),volumeSlider=document.getElementById('volume-slider'),countdownTag=document.getElementById('countdown-tag');
const modalDifficulty=document.getElementById('modal-difficulty'),modalTheme=document.getElementById('modal-theme'),modalSound=document.getElementById('modal-sound'),modalModes=document.getElementById('modal-modes'),modalCustomText=document.getElementById('modal-custom-text'),modalAchievements=document.getElementById('modal-achievements'),modalPpmInfo=document.getElementById('modal-ppm-info'),modalWelcome=document.getElementById('modal-welcome'),modalRestartConfirm=document.getElementById('modal-restart-confirm'),modalModeHelp=document.getElementById('modal-mode-help'),modeHelpClose=document.getElementById('mode-help-close'),modeHelpIcon=document.getElementById('mode-help-icon'),modeHelpTitle=document.getElementById('mode-help-title'),modeHelpDescription=document.getElementById('mode-help-description'),modeHelpRules=document.getElementById('mode-help-rules'),confirmRestartBtn=document.getElementById('confirm-restart-btn'),cancelRestartBtn=document.getElementById('cancel-restart-btn');

const MODE_HELP={default:{icon:'📖',title:'Padrão',description:'Treine sua digitação no formato clássico.',rules:['Complete uma sequência de 5 frases.','Acompanhe PPM, precisão, tempo e progresso em tempo real.','Ao terminar, use “Continuar Treinando” para gerar uma nova sequência.']},fury:{icon:'🔥',title:'Fúria',description:'Construa uma sequência de acertos e aumente sua velocidade.',rules:['Acertos consecutivos aumentam seu nível de Fúria.','Um erro quebra a sequência.','Ao terminar a frase, use “Nova Sequência” para continuar.']},survival:{icon:'💀',title:'Sobrevivência',description:'Cada caractere é uma corrida contra o relógio.',rules:['Você possui vidas limitadas.','Cada caractere tem um tempo de vida.','Ao perder, use “Tentar Novamente” para recomeçar.']},sniper:{icon:'🎯',title:'Precisão Extrema',description:'Erros custam caro.',rules:['Evite erros consecutivos.','Erros podem recuar seu progresso.','Ao terminar ou falhar, use “Nova Tentativa”.']},wordhunt:{icon:'🧩',title:'Caça-Palavras',description:'Descubra e digite as palavras corretamente.',rules:['A palavra exibida é embaralhada.','Corrija erros com Backspace.','Ao terminar a sequência, use “Caçar Novamente”.']},casino:{icon:'💰',title:'Cassino',description:'Aposte fichas na sua própria performance.',rules:['Aposta e recompensa dependem da precisão.','Aumente sua banca com rodadas bem-sucedidas.','Use “Nova Rodada” para continuar.']},marathon:{icon:'🏃',title:'Maratona',description:'Digite o máximo de palavras antes do tempo acabar.',rules:['O cronômetro começa na primeira palavra.','Cada palavra concluída aumenta sua pontuação.','Ao acabar o tempo, use “Nova Maratona”.']},memory:{icon:'🧠',title:'Memória',description:'Memorize o texto antes que ele desapareça.',rules:['O texto fica visível durante o período de memorização.','Depois ele desaparece e você deve digitar de memória.','Use “Memorizar Novamente” para outra tentativa.']},wave:{icon:'🌊',title:'Onda',description:'Complete uma sequência de palavras antes que o tempo de cada palavra termine.',rules:['Cada palavra possui seu próprio tempo.','Acertar avança para a próxima.','Ao concluir a sequência, use “Nova Onda”.']},rpg:{icon:'⚔️',title:'RPG',description:'Transforme sua digitação em combate.',rules:['Cada frase causa dano ao monstro.','Erros causam dano ao jogador.','Ao derrotar o monstro, use “Continuar Batalhando”.']}};

export function openModal(modal){if(!modal)return;modal.classList.add('active');if(modal===modalWelcome){document.body.classList.add('tutorial-open');const i=document.getElementById('hidden-input');if(i){i.blur();i.disabled=true;i.setAttribute('inputmode','none')}}}
export function closeModal(modal){if(!modal)return;modal.classList.remove('active');if(modal===modalWelcome){document.body.classList.remove('tutorial-open');const i=document.getElementById('hidden-input');if(i){i.disabled=false;i.setAttribute('inputmode','text')}}}
export function disableTimerMode(){if(!state.isTimerMode)return;state.isTimerMode=false;clearInterval(state.timerModeInterval);state.timerModeInterval=null;if(countdownTag){countdownTag.classList.add('hidden');countdownTag.classList.remove('warning')}const b=document.getElementById('timer-mode-btn');if(b){b.textContent='⏱️ Contra-Relógio';b.classList.remove('active')}}
function openModeHelp(){const help=MODE_HELP[getModeId()]||MODE_HELP.default;if(modeHelpIcon)modeHelpIcon.textContent=help.icon;if(modeHelpTitle)modeHelpTitle.textContent=`Como jogar: ${help.title}`;if(modeHelpDescription)modeHelpDescription.textContent=help.description;if(modeHelpRules)modeHelpRules.innerHTML=help.rules.map((r,i)=>`<div class="mode-help-rule"><span>${i+1}</span><p>${r}</p></div>`).join('');openModal(modalModeHelp)}
export function renderHistoryChart(modeId){const chart=document.getElementById('history-chart');if(!chart)return;const stats=getModeStats(modeId),history=stats.ppmHistory||[],avgEl=document.getElementById('history-avg');chart.innerHTML='';if(!history.length){if(avgEl)avgEl.textContent='Média: 0';chart.innerHTML='<span style="font-size:.6rem;color:var(--text-muted);width:100%;text-align:center;padding:8px 0;">Nenhum dado ainda. Comece a digitar!</span>';return}const avg=Math.round(history.reduce((a,b)=>a+b,0)/history.length);if(avgEl)avgEl.textContent=`Média: ${avg}`;const maxPPM=Math.max(10,...history,1);history.forEach(v=>{const d=document.createElement('div');d.className=`history-dot ${v>0?'active':''}`;d.style.height=`${Math.max(4,(v/maxPPM)*38)}px`;if(v>0){const t=document.createElement('span');t.className='dot-tooltip';t.textContent=`${v} PPM`;d.appendChild(t)}chart.appendChild(d)})}
function updateMedalLabels(){const diff=state.currentDifficulty;if(diff==='custom')return;const l=DIFFICULTY_THRESHOLDS[diff];if(reqTime15)reqTime15.textContent=`Tempo ≤ ${l.time15}s`;if(reqTime30)reqTime30.textContent=`Tempo ≤ ${l.time30}s`;if(reqSpeed60)reqSpeed60.textContent=`${l.speed60}+ PPM`}
export function setDifficulty(val){state.currentDifficulty=val;if(difficultyTriggerText)difficultyTriggerText.textContent=DIFFICULTY_NAMES[val]||'Fácil';if(modalDifficulty)modalDifficulty.querySelectorAll('.modal-option-btn').forEach(b=>b.classList.toggle('selected',b.dataset.value===val));const custom=val==='custom';if(standardMedals)standardMedals.classList.toggle('hidden',custom);if(customMedals)customMedals.classList.toggle('hidden',!custom);if(medalsTitle)medalsTitle.textContent=custom?'🏅 Medalhas (Modo Personalizado)':'🏅 Medalhas (Modo Padrão)';if(editCustomBtn)editCustomBtn.classList.toggle('hidden',!custom);if(difficultyTag)difficultyTag.textContent=`Nível: ${DIFFICULTY_NAMES[val]||val}`;updateMedalLabels();loadAchievements();initTest();if(custom&&(!state.customUserText||state.customUserText.trim().length<10))openModal(modalCustomText)}
export function setTheme(val){state.currentTheme=val;audioEngine.playThemeSwitch();document.documentElement.classList.add('no-transitions');document.documentElement.setAttribute('data-theme',val);localStorage.setItem('selectedTheme',val);if(themeTriggerText)themeTriggerText.textContent=THEME_NAMES[val]||'Azul Marinho';if(modalTheme)modalTheme.querySelectorAll('.modal-option-btn').forEach(b=>b.classList.toggle('selected',b.dataset.value===val));trackThemeChange(val);requestAnimationFrame(()=>requestAnimationFrame(()=>document.documentElement.classList.remove('no-transitions')))}
export function setSoundProfile(val){audioEngine.setProfile(val);localStorage.setItem('selectedSoundProfile',val);if(soundTriggerText)soundTriggerText.textContent=SOUND_NAMES[val]||'Thock Mecânico';if(modalSound)modalSound.querySelectorAll('.modal-option-btn').forEach(b=>b.classList.toggle('selected',b.dataset.value===val));audioEngine.playKey(false)}
export function loadSavedSettings(){const theme=localStorage.getItem('selectedTheme')||'default',profile=localStorage.getItem('selectedSoundProfile')||'thock',volume=localStorage.getItem('selectedSoundVolume')||'0.9';setTheme(theme);setSoundProfile(profile);audioEngine.setVolume(volume);if(volumeSlider)volumeSlider.value=volume;updateGlobalLevelUI()}
export function setupModalTriggers(){
  document.getElementById('mode-help-trigger')?.remove();
  let modeInfoBtn=document.getElementById('mode-info-btn');
  if(!modeInfoBtn){modeInfoBtn=document.createElement('button');modeInfoBtn.type='button';modeInfoBtn.id='mode-info-btn';modeInfoBtn.className='mode-info-btn';modeInfoBtn.setAttribute('aria-label','Como jogar este modo');modeInfoBtn.title='Como jogar este modo';modeInfoBtn.textContent='ℹ️';document.getElementById('mode-status-tag')?.insertAdjacentElement('afterend',modeInfoBtn)}
  modeInfoBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openModeHelp()});
  document.addEventListener('click',e=>{const target=e.target.closest('.select-trigger,.btn-achievements-trigger');if(!target)return;if(target.id==='mode-trigger'){renderModeList();openModal(modalModes)}else if(target.id==='difficulty-trigger')openModal(modalDifficulty);else if(target.id==='theme-trigger')openModal(modalTheme);else if(target.id==='sound-trigger')openModal(modalSound);else if(target.id==='achievements-trigger'){renderAchievementsUI();openModal(modalAchievements)}});
  document.addEventListener('click',e=>{const close=e.target.closest('.modal-close');if(close){const m=document.getElementById(close.dataset.close);if(m)closeModal(m);return}if(e.target.classList.contains('modal-overlay'))closeModal(e.target)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')[modalDifficulty,modalTheme,modalSound,modalModes,modalCustomText,modalAchievements,modalPpmInfo,modalWelcome,modalRestartConfirm,modalModeHelp].forEach(closeModal)});
  document.addEventListener('click',e=>{const option=e.target.closest('.modal-option-btn');if(!option)return;const parent=option.closest('.modal-overlay');if(!parent)return;const value=option.dataset.value;if(!value)return;if(parent.id==='modal-sound'&&e.target.closest('.sound-preview-btn'))return;if(parent.id==='modal-difficulty'){setDifficulty(value);closeModal(parent)}else if(parent.id==='modal-theme'){setTheme(value);closeModal(parent)}else if(parent.id==='modal-sound'){setSoundProfile(value);closeModal(parent)}else if(parent.id==='modal-modes'){setMode(value);closeModal(parent);if(modeTriggerText)modeTriggerText.textContent=MODE_NAMES[value]||value;const stats=getModeStats(value),best=document.getElementById('best-ppm-val');if(best)best.textContent=stats.bestPPM||0;renderHistoryChart(value);updateGlobalLevelUI()}});
  document.addEventListener('click',e=>{const preview=e.target.closest('.sound-preview-btn');if(!preview)return;e.preventDefault();e.stopPropagation();const value=preview.dataset.value;if(value)audioEngine.playPreview(value)});
  document.addEventListener('click',e=>{if(e.target.closest('#ppm-info-btn'))openModal(modalPpmInfo);if(e.target.closest('#mode-info-btn'))openModeHelp()});
  if(saveCustomTextBtn)saveCustomTextBtn.addEventListener('click',()=>{const value=customTextInput.value.trim();if(value.length<10){customTextError?.classList.remove('hidden');return}state.customUserText=value;localStorage.setItem('customUserText',value);closeModal(modalCustomText);initTest()});
  if(editCustomBtn)editCustomBtn.addEventListener('click',()=>{if(customTextInput)customTextInput.value=state.customUserText;if(customTextError)customTextError.classList.add('hidden');openModal(modalCustomText)});
  if(volumeSlider)volumeSlider.addEventListener('input',e=>{audioEngine.setVolume(e.target.value);localStorage.setItem('selectedSoundVolume',e.target.value)});
  if(restartBtn)restartBtn.addEventListener('click',e=>{e.preventDefault();const b=document.getElementById('restart-btn');if(b&&!b.disabled)openModal(modalRestartConfirm)});
  if(confirmRestartBtn)confirmRestartBtn.addEventListener('click',e=>{e.preventDefault();closeModal(modalRestartConfirm);initTest()});
  if(cancelRestartBtn)cancelRestartBtn.addEventListener('click',e=>{e.preventDefault();closeModal(modalRestartConfirm)});
  if(modeHelpClose)modeHelpClose.addEventListener('click',e=>{e.preventDefault();closeModal(modalModeHelp)});
  const tutorialBtn=document.getElementById('tutorial-btn');if(tutorialBtn)tutorialBtn.addEventListener('click',e=>{e.preventDefault();openModal(modalWelcome)});
  document.getElementById('feedback-trigger')?.addEventListener('click',e=>{e.preventDefault();window.open('https://forms.gle/KsACEZfVzteRzm8s9','_blank')});
}
export function showWelcomeModal(){openModal(modalWelcome)}
export function toggleTimerMode(){const mode=getModeHandler();if(mode?.hasTimer){showToast('⚠️ Este modo já possui temporizador próprio!');return}state.isTimerMode=!state.isTimerMode;const b=document.getElementById('timer-mode-btn');if(b){b.textContent=state.isTimerMode?'⏱️ Modo Normal':'⏱️ Contra-Relógio';b.classList.toggle('active',state.isTimerMode)}if(countdownTag){countdownTag.classList.toggle('hidden',!state.isTimerMode);if(state.isTimerMode)countdownTag.textContent=`⏱️ ${state.timerModeLimit}s`;else countdownTag.classList.remove('warning')}clearInterval(state.timerModeInterval);state.timerModeInterval=null;initTest()}
export function setupShareButton(){const b=document.getElementById('share-site-btn');if(!b)return;b.addEventListener('click',()=>{const url=window.location.href,text='⌨️ Mestre da Digitação - Teste sua velocidade e precisão!';if(navigator.share)navigator.share({title:'Mestre da Digitação',text,url}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(`${text}\n\n${url}`).then(()=>showToast('✅ Link copiado!')).catch(()=>fallbackShare(url,text));else fallbackShare(url,text)})}
function fallbackShare(url,text){const ta=document.createElement('textarea');ta.value=`${text}\n\n${url}`;ta.style.cssText='position:fixed;opacity:0;left:-9999px;';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');showToast('✅ Link copiado!')}catch(_){showToast(`📋 Copie o link: ${url}`)}ta.remove()}
function showToast(msg){document.querySelector('.toast-message')?.remove();const d=document.createElement('div');d.className='toast-message';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>{d.style.opacity='0';d.style.transition='opacity .3s';setTimeout(()=>d.remove(),300)},2000)}