// js/modules/utils.js
export const DIFFICULTY_NAMES = { easy: 'Fácil', medium: 'Médio', hard: 'Difícil', custom: 'Personalizado' };
export const THEME_NAMES = {
  default: 'Azul Marinho',
  dracula: 'Dracula Cyber',
  midnight: 'Meia-Noite Roxo',
  charcoal: 'Carvão Minimalista',
  'nordic-dark': 'Nórdico Escuro',
  light: 'Claro Clean',
  paper: 'Papel Sépia',
  pastel: 'Soft Pastel',
  'nordic-light': 'Nórdico Claro',
  amber: 'Amber Retrô',
  matrix: 'Matrix Terminal',
  'terminal-blue': 'IBM Blue Terminal',
  synthwave: 'Synthwave 80s',
  sunset: 'Pôr do Sol',
  emerald: 'Floresta Esmeralda'
};
export const SOUND_NAMES = {thock:'Thock Mecânico',pop:'Pop Suave',retro:'Retrô Cyber 80s',typewriter:'Máquina de Escrever',clack:'Clack Seco',deep:'Deep Grave',clicky:'Clicky Preciso',silent:'Silencioso / Muto'};
export const DIFFICULTY_THRESHOLDS = {easy:{time15:15,time30:30,speed60:50},medium:{time15:20,time30:40,speed60:60},hard:{time15:30,time30:60,speed60:70}};
export const SENTENCES = {
  easy:["O sol ilumina a manhã tranquila.","Um café quente renova as energias.","As folhas secas caem no outono.","Caminhar na praia acalma a mente.","O aroma do pão fresco é delicioso.","Passarinhos cantam na janela do quarto.","A lua cheia brilha no céu estrelado.","Plantar flores traz cor ao jardim.","A água da fonte é bem fresca.","O vento suave balança as árvores.","Ler um bom livro diverte bastante.","A chuva fina molha a calçada.","Comer frutas faz bem à saúde.","Um sorriso sincero muda o dia.","Gatos adoram dormir ao sol da tarde.","A montanha alta desafia os aventureiros.","Pintar um quadro desperta a imaginação.","Cães correm felizes pelo parque verde.","O bolo de fubá assa no forno.","A noite traz paz e descanso merecido."],
  medium:["Enquanto as ondas quebram na areia, o farol ilumina o caminho dos navegantes.","Preparar uma receita antiga traz memórias afetuosas e aromas inesquecíveis para a cozinha.","As estações do ano transformam a paisagem com cores, aromas e sensações totalmente diferentes.","Na calma da biblioteca, o som das páginas viradas acompanha a busca pelo conhecimento.","O jardineiro cuida das rosas com paciência, sabendo que cada flor exige seu próprio tempo.","Viajar para lugares desconhecidos abre novos horizontes e enriquece a nossa bagagem cultural.","A orquestra começou a tocar suavemente, encantando a plateia com uma melodia inesquecível.","Observar o pôr do sol no horizonte é um lembrete diário da beleza simples da vida.","Pequenos hábitos diários de gentileza têm o poder de transformar relacionamentos e ambientes.","O aroma de terra molhada após a tempestade traz uma sensação única de renovação.","Aprender a tocar um instrumento exige dedicação diária, foco e muita paixão pela música.","No topo da colina, a vista panorâmica da cidade ao amanhecer revela um espetáculo grandioso.","A arte de cozinhar envolve combinar temperos simples para criar sabores surpreendentes.","Reler um clássico da literatura nos permite descobrir detalhes que antes passaram despercebidos.","O canto dos pássaros ao alvorecer anuncia a chegada de mais uma oportunidade para recomeçar.","Caminhar por trilhas florestais nos reconecta com a natureza e purifica os pensamentos.","O pintor mistura cores primárias na paleta até encontrar o tom exato para sua obra.","Guardar boas recordações em fotografias ajuda a preservar momentos especiais com quem amamos.","Uma xícara de chá bem quente é o acompanhamento perfeito para uma tarde fria de chuva.","A determinação dos atletas na maratona inspira todos aqueles que assistem à competição."],
  hard:["Entre os vales sinuosos e as montanhas cobertas de névoa, a antiga civilização deixou vestígios arquitetônicos surpreendentes.","A gastronomia artesanal combina tradições seculares com técnicas modernas, valorizando ingredientes orgânicos cultivados por pequenos produtores.","O silêncio sepulcral das galerias de arte permite aos visitantes contemplar as nuances das pinceladas e a melancolia das telas.","Navegar por mares agitados exige coragem inabalável, conhecimento profundo das marés e um respeito absoluto pelas forças da natureza.","A preservação dos ecossistemas florestais garante o equilíbrio climático global, protegendo espécies raras e mantendo a biodiversidade.","Durante o rigoroso inverno nórdico, o espetáculo luminoso da aurora boreal tinge o céu noturno com tons vibrantes de verde e violeta.","A literatura clássica atravessa séculos sem perder sua relevância, pois retrata as paixões, dilemas morais e contradições humanas.","Arquitetos renomados buscam harmonizar o design urbano com espaços verdes, promovendo a sustentabilidade e o bem-estar coletivo.","O artesão dedica horas esculpindo a madeira bruta com ferramentas manuais, transformando um tronco inerte em uma escultura viva.","Enquanto a chuva torrencial batia contra as vidraças do casarão, a família se reunia ao redor da lareira para ouvir histórias antigas.","A complexidade do ecossistema marinho revela um mundo fascinante de corais coloridos, peixes exóticos e criaturas misteriosas.","Cultivar a paciência e a resiliência nos momentos adversos permite-nos superar obstáculos aparentemente intransponíveis com serenidade.","O festival de música atrai multidões entusiasmadas, celebrando a diversidade cultural por meio de ritmos vibrantes e performances ao ar livre.","As expedições botânicas do século dezenove catalogaram milhares de plantas medicinais, contribuindo para o avanço do conhecimento científico.","Caminhar pelas vielas de pedras de uma cidade histórica é como viajar no tempo, vislumbrando séculos de arte e tradição preservadas.","O sabor encorpado de um bom vinho envelhecido em barris de carvalho reflete o clima do vinhedo e a dedicação do enólogo.","Decifrar os mistérios do universo demanda observação meticulosa das estrelas, cálculos rigorosos e um desejo incessante de exploração.","A sinfonia composta no período romântico alterna momentos de intensa dramaticidade com passagens suaves de pura delicadeza poética.","A prática regular de meditação e exercícios de respiração reduz o estresse, promovendo o equilíbrio emocional e a clareza mental.","Nos mercados tradicionais do oriente, o aroma penetrante de especiarias raras mescla-se ao colorido das tecelagens manuais e ao burburinho local."]};
export const MODE_MEDALS={
  default:[{id:'accuracy',icon:'🎯',name:'Precisão Total',req:'≥ 90% Precisão'},{id:'time15',icon:'⚡',name:'Relâmpago',req:'Tempo ≤ 15s'},{id:'time30',icon:'🥈',name:'Arrancada',req:'Tempo ≤ 30s'},{id:'speed60',icon:'🥇',name:'Mestre',req:'50+ PPM'}],
  fury:[{id:'fury_50',icon:'🔥',name:'Fúria Incontrolável',req:'Streak de 50 caracteres'},{id:'fury_100',icon:'⚡',name:'Raio Furioso',req:'Streak de 100 caracteres'}],
  survival:[{id:'survive_5',icon:'❤️',name:'Sobrevivente',req:'Completar com 5 vidas'},{id:'survive_1',icon:'💀',name:'Quase Morto',req:'Completar com 1 vida'}],
  sniper:[{id:'sniper_perfect',icon:'🎯',name:'Atirador de Elite',req:'0 erros na frase'},{id:'sniper_comeback',icon:'🔄',name:'Recuperação',req:'Completar após 2 erros'}],
  wordhunt:[{id:'hunt_10',icon:'🧩',name:'Caçador Iniciante',req:'Encontrar 10 palavras'},{id:'hunt_20',icon:'🏆',name:'Mestre Caçador',req:'Encontrar 20 palavras'}],
  casino:[{id:'casino_500',icon:'💰',name:'Milionário',req:'Acumular 500 fichas'},{id:'casino_lucky',icon:'🍀',name:'Sorte Grande',req:'Ganhar 3 apostas seguidas'}],
  marathon:[{id:'marathon_50',icon:'🏃',name:'Maratonista',req:'50 palavras em 60s'},{id:'marathon_100',icon:'🚀',name:'Usain Bolt',req:'100 palavras em 60s'}],
  memory:[{id:'memory_perfect',icon:'🧠',name:'Mente de Elefante',req:'100% de memória'},{id:'memory_fast',icon:'⏱️',name:'Memória Relâmpago',req:'Completar em < 5s'}],
  wave:[{id:'wave_10',icon:'🌊',name:'Surfista',req:'Completar 10 ondas'},{id:'wave_perfect',icon:'🏄',name:'Onda Perfeita',req:'Todas as ondas sem erro'}],
  rpg:[{id:'rpg_lv5',icon:'⚔️',name:'Guerreiro',req:'Alcançar nível 5'},{id:'rpg_lv10',icon:'🛡️',name:'Cavaleiro',req:'Alcançar nível 10'},{id:'rpg_100_hits',icon:'💥',name:'Combo Perfeito',req:'100 acertos no RPG'}]
};
export const ACHIEVEMENTS_LIST=[{id:'surgeon',icon:'🎯',title:'Cirurgião do Teclado',desc:'2 frases seguidas com 100% de precisão'},{id:'slow_steady',icon:'🐢',title:'Devagar e Sempre',desc:'Frase com menos de 20 PPM e 100% de precisão'},{id:'light_speed',icon:'⚡',title:'Velocidade da Luz',desc:'Ultrapassar 70 PPM em qualquer frase'},{id:'hot_finger',icon:'🔥',title:'Dedo Quente',desc:'Média acima de 50 PPM em 5 frases seguidas'},{id:'fast_imperfect',icon:'🏎️',title:'Velozes e Imperfeitos',desc:'Mais de 60 PPM com precisão abaixo de 80%'},{id:'night_owl',icon:'🦉',title:'Coruja Noturna',desc:'Treinar entre 00:00 e 05:00 da manhã'},{id:'morning_coffee',icon:'☕',title:'Café com Teclado',desc:'Treinar entre 06:00 e 08:00 da manhã'},{id:'streak_3',icon:'📅',title:'Imparável',desc:'Praticar no site por 2 dias seguidos'},{id:'chameleon',icon:'🎨',title:'Camaleão Visual',desc:'Alternar entre 4 temas na mesma sessão'},{id:'hacker_80s',icon:'📟',title:'Hacker dos Anos 80',desc:'Concluir frase nos temas Matrix ou Amber'},{id:'space_destroyer',icon:'⌨️',title:'Destruidor de Espaços',desc:'Acumular 500 barras de espaço pressionadas'},{id:'level_5',icon:'🌟',title:'Aprendiz',desc:'Alcançar nível 5 global'},{id:'level_10',icon:'🌟',title:'Discípulo',desc:'Alcançar nível 10 global'},{id:'level_25',icon:'🌟',title:'Mestre',desc:'Alcançar nível 25 global'},{id:'level_50',icon:'🌟',title:'Lenda',desc:'Alcançar nível 50 global'},{id:'battle_10',icon:'⚔️',title:'Guerreiro Iniciante',desc:'Vença 10 batalhas no RPG'},{id:'battle_50',icon:'⚔️',title:'Herói',desc:'Vença 50 batalhas no RPG'},{id:'battle_100',icon:'⚔️',title:'Lendário',desc:'Vença 100 batalhas no RPG'},{id:'perfect_10',icon:'🎯',title:'Perfeccionista',desc:'10 rodadas perfeitas (100% precisão)'},{id:'perfect_50',icon:'🎯',title:'Mestre da Perfeição',desc:'50 rodadas perfeitas'},{id:'perfect_100',icon:'🎯',title:'Deus da Precisão',desc:'100 rodadas perfeitas'},{id:'rpg_win_50',icon:'👑',title:'Rei do RPG',desc:'Vença 50 batalhas no modo RPG'}];
export const state={
  currentDifficulty:'easy',currentTheme:'default',currentModeId:'default',customUserText:localStorage.getItem('customUserText')||'',isTimerMode:false,timerModeLimit:30,timerModeInterval:null,currentPPM:0,isRunning:false,totalTyped:0,errors:0,startTime:null,previousInput:'',currentText:'',timerInterval:null,modeStats:JSON.parse(localStorage.getItem('mestre_mode_stats'))||{},userStats:JSON.parse(localStorage.getItem('mestre_user_stats'))||{unlockedAchievements:[],spaceCount:0,themesUsed:[],perfectStreak:0,recentWpms:[],lastActiveDate:null,dayStreak:0,globalXP:0,globalLevel:1,totalPerfectRounds:0,totalBattlesWon:0,totalTypedChars:0}
};
export function saveState(){localStorage.setItem('mestre_mode_stats',JSON.stringify(state.modeStats));localStorage.setItem('mestre_user_stats',JSON.stringify(state.userStats));localStorage.setItem('customUserText',state.customUserText)}
export function getModeStats(modeId){if(!state.modeStats[modeId])state.modeStats[modeId]={ppmHistory:[],bestPPM:0,bestAccuracy:0,bestTime:null,rounds:0,totalTyped:0,medalCounts:{}};return state.modeStats[modeId]}
export function getLocalDateStr(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}