// js/modes/memory.js
import { state } from '../modules/utils.js';
import { incrementMedal } from '../modules/stats.js';

export default {
  id:'memory',name:'Memória',linear:true,hasTimer:false,hidden:false,revealTimeout:null,typed:'',errors:0,startTime:null,textShown:'',displayTime:3,
  init(text){const config=({easy:{displayTime:5},medium:{displayTime:3.5},hard:{displayTime:2}})[state.currentDifficulty]||{displayTime:5};this.displayTime=config.displayTime;this.hidden=false;this.typed='';this.errors=0;this.startTime=null;this.textShown=String(text??state.currentText).normalize('NFC');state.currentText=this.textShown;this.render(this.textShown);this.resetInput();this.updateProgress(0);const tag=document.getElementById('mode-status-tag');if(tag)tag.textContent='🧠 Memorize o texto...';const display=document.getElementById('text-display'),input=document.getElementById('hidden-input');if(display){display.style.opacity='1';display.style.visibility='visible';}if(input)input.disabled=true;if(this.revealTimeout)clearTimeout(this.revealTimeout);this.revealTimeout=setTimeout(()=>{this.revealTimeout=null;this.hidden=true;if(display){display.style.opacity='0';display.style.visibility='hidden';}if(tag)tag.textContent='🧠 Digite de memória!';if(input)input.disabled=false;},this.displayTime*1000);},
  render(text){const d=document.getElementById('text-display');if(d)d.innerHTML=String(text).split('').map((ch,i)=>`<span class="char ${i===0?'current':''}">${ch}</span>`).join('');},
  resetInput(){const i=document.getElementById('hidden-input');if(i)i.value='';},
  updateProgress(typed){const total=this.textShown.length||state.currentText.length,p=total?Math.min(100,Math.round(typed/total*100)):0,f=document.getElementById('progress-fill'),t=document.getElementById('progress-text'),q=document.getElementById('progress-percent');if(f)f.style.width=`${p}%`;if(t)t.textContent=`${typed} / ${total} caracteres`;if(q)q.textContent=`${p}%`;},
  handleInput(value){if(!this.hidden)return{playError:false};const text=this.textShown||state.currentText,prevLen=this.typed.length;this.typed=value;if(!this.startTime&&value.length)this.startTime=performance.now();const chars=value.split('');let errors=0;document.querySelectorAll('#text-display .char').forEach((span,idx)=>{const typed=chars[idx],target=text[idx];span.classList.remove('correct','incorrect','current');if(typed==null){if(idx===chars.length)span.classList.add('current')}else if(typed===target){span.classList.add('correct');span.style.color='var(--accent)'}else{span.classList.add('incorrect');errors++}});this.errors=errors;this.updateProgress(chars.length);const accuracy=chars.length?Math.round(((chars.length-errors)/chars.length)*100):100,av=document.getElementById('accuracy-val');if(av)av.textContent=`${accuracy}%`;const elapsed=this.startTime?Math.max(1,(performance.now()-this.startTime)/1000):1,wpm=Math.round((chars.length/5)/(elapsed/60)),pv=document.getElementById('ppm-val');if(pv)pv.textContent=wpm;state.currentPPM=wpm;if(chars.length>=text.length){if(this.revealTimeout){clearTimeout(this.revealTimeout);this.revealTimeout=null}return{done:true,accuracy,wpm,playError:false}}return{done:false,playError:chars.length>prevLen&&chars.length>0&&chars[chars.length-1]!==text[chars.length-1]};},
  reset(){if(this.revealTimeout)clearTimeout(this.revealTimeout);this.revealTimeout=null;this.hidden=false;this.textShown='';this.typed='';this.errors=0;this.startTime=null;const d=document.getElementById('text-display'),i=document.getElementById('hidden-input');if(d){d.style.opacity='1';d.style.visibility='visible';d.querySelectorAll('.char').forEach(span=>span.style.removeProperty('color'));}if(i)i.disabled=false;const tag=document.getElementById('mode-status-tag');if(tag)tag.textContent='🧠 Modo Memória';},
  destroy(){if(this.revealTimeout)clearTimeout(this.revealTimeout);this.revealTimeout=null;const d=document.getElementById('text-display'),i=document.getElementById('hidden-input');if(d){d.style.opacity='1';d.style.visibility='visible';d.querySelectorAll('.char').forEach(span=>span.style.removeProperty('color'));}if(i)i.disabled=false;},
  checkMedals(accuracy,wpm,time){if(accuracy===100)incrementMedal(this.id,'memory_perfect');if(time<5)incrementMedal(this.id,'memory_fast');},
  getMetrics(){const chars=this.typed.length,accuracy=chars?Math.round(((chars-this.errors)/chars)*100):100,elapsed=this.startTime?Math.max(1,(performance.now()-this.startTime)/1000):1;return{accuracy,wpm:Math.round((chars/5)/(elapsed/60))};},
  getResultMessage(accuracy,wpm){return`🧠 ${accuracy}% precisão de memória | ${wpm} PPM`;}
};
